[package]
name = "anon-say"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
image = "0.24"
imageproc = "0.23"
rusttype = "0.9.3"
viuer = "0.7.1"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
